spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: pung.971212
    password: uaqe wbev iljw gxjx
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db1.c0kt3mulsjo8.ap-northeast-2.rds.amazonaws.com:3306/board
    username: admin
    password: 1q2w3e4r

mybatis:
  mapper-locations:
    - /mappers/*.xml

jwt:
  secret: mtsxGgbvzr62ATIYKbO/kok57jiG+6H7BU83CjkWL4AAVTF7OqvhMMH3UODsXjE7H2+nJxY2xcF0FlKNrOPKxA==